In [1]:
#importing necessary libraries
import numpy as np
import pandas as pd

In [2]:
#importing dataset

Train=pd.read_excel("Data_Train.xlsx")
Test=pd.read_excel("Test_set.xlsx")

In [3]:
# seeing how the training data looks
Train.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897  
1    05:50         13:15   7h 25m     2 stops         No info   7662  
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882  
3    18:05         23:30   5h 25m      1 stop         No info   6218  
4    16:50         21:35   4h 45m      1 stop         No info  13302

In [4]:
# seeing how the Testing data looks
Test.head()

Airline Date_of_Journey    Source Destination            Route  \
0        Jet Airways       6/06/2019     Delhi      Cochin  DEL → BOM → COK   
1             IndiGo      12/05/2019   Kolkata    Banglore  CCU → MAA → BLR   
2        Jet Airways      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
3  Multiple carriers      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
4           Air Asia      24/06/2019  Banglore       Delhi        BLR → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops              Additional_Info  
0    17:30  04:25 07 Jun  10h 55m      1 stop                      No info  
1    06:20         10:20       4h      1 stop                      No info  
2    19:15  19:00 22 May  23h 45m      1 stop  In-flight meal not included  
3    08:00         21:00      13h      1 stop                      No info  
4    23:55  02:45 25 Jun   2h 50m    non-stop                      No info

In [5]:
# priniting the details about the datasets
print(Train.shape)
print(Test.shape)

(10683, 11)
(2671, 10)


In [6]:
print(Train.info())
print(Test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64 
dtypes: int64(1), object(10)
memory usage: 918.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2671 entries, 0 to 2670
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          2671 non-null   object
 1   D

In [7]:
print(Train.isnull().sum())
print(Test.isnull().sum())

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64
Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
dtype: int64


This means that there was only one row having missing values which we have removed

In [8]:
print(Train.columns)
print(Test.columns)

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')
Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info'],
      dtype='object')


In [9]:
print("No. of rows:",len(Train))
print("No. of rows:",len(Test))

No. of rows: 10683
No. of rows: 2671


In [10]:
#converting the data type to data-time format and adding new columns
# Train Set
Train["Journey_Date"]=pd.to_datetime(Train["Date_of_Journey"], format="%d/%M/%Y").dt.day
Train["Journey_month"]=pd.to_datetime(Train["Date_of_Journey"], format="%d/%M/%Y").dt.month
Train.head()

Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      24/03/2019  Banglore   New Delhi              BLR → DEL   
1    Air India       1/05/2019   Kolkata    Banglore  CCU → IXR → BBI → BLR   
2  Jet Airways       9/06/2019     Delhi      Cochin  DEL → LKO → BOM → COK   
3       IndiGo      12/05/2019   Kolkata    Banglore        CCU → NAG → BLR   
4       IndiGo      01/03/2019  Banglore   New Delhi        BLR → NAG → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897   
1    05:50         13:15   7h 25m     2 stops         No info   7662   
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882   
3    18:05         23:30   5h 25m      1 stop         No info   6218   
4    16:50         21:35   4h 45m      1 stop         No info  13302   

   Journey_Date  Journey_month  
0            24              1  
1             1              1  
2             9              1  
3            12              1  
4             1              1

In [11]:
#converting the data type to data-time format and adding new columns
#Test Set
Test["Journey_Date"]=pd.to_datetime(Test["Date_of_Journey"], format="%d/%M/%Y").dt.day
Test["Journey_month"]=pd.to_datetime(Test["Date_of_Journey"], format="%d/%M/%Y").dt.month
Test.head()

Airline Date_of_Journey    Source Destination            Route  \
0        Jet Airways       6/06/2019     Delhi      Cochin  DEL → BOM → COK   
1             IndiGo      12/05/2019   Kolkata    Banglore  CCU → MAA → BLR   
2        Jet Airways      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
3  Multiple carriers      21/05/2019     Delhi      Cochin  DEL → BOM → COK   
4           Air Asia      24/06/2019  Banglore       Delhi        BLR → DEL   

  Dep_Time  Arrival_Time Duration Total_Stops              Additional_Info  \
0    17:30  04:25 07 Jun  10h 55m      1 stop                      No info   
1    06:20         10:20       4h      1 stop                      No info   
2    19:15  19:00 22 May  23h 45m      1 stop  In-flight meal not included   
3    08:00         21:00      13h      1 stop                      No info   
4    23:55  02:45 25 Jun   2h 50m    non-stop                      No info   

   Journey_Date  Journey_month  
0             6              1  
1            12              1  
2            21              1  
3            21              1  
4            24              1

In [12]:
#droping the original date feature
Train.drop(labels="Date_of_Journey", inplace=True, axis=1)
Train.head()

Airline    Source Destination                  Route Dep_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    22:20   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR    05:50   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK    09:25   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR    18:05   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL    16:50   

   Arrival_Time Duration Total_Stops Additional_Info  Price  Journey_Date  \
0  01:10 22 Mar   2h 50m    non-stop         No info   3897            24   
1         13:15   7h 25m     2 stops         No info   7662             1   
2  04:25 10 Jun      19h     2 stops         No info  13882             9   
3         23:30   5h 25m      1 stop         No info   6218            12   
4         21:35   4h 45m      1 stop         No info  13302             1   

   Journey_month  
0              1  
1              1  
2              1  
3              1  
4              1

In [13]:
#droping the original date feature
Test.drop(labels="Date_of_Journey", inplace=True, axis=1)
Train.head()

Airline    Source Destination                  Route Dep_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL    22:20   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR    05:50   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK    09:25   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR    18:05   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL    16:50   

   Arrival_Time Duration Total_Stops Additional_Info  Price  Journey_Date  \
0  01:10 22 Mar   2h 50m    non-stop         No info   3897            24   
1         13:15   7h 25m     2 stops         No info   7662             1   
2  04:25 10 Jun      19h     2 stops         No info  13882             9   
3         23:30   5h 25m      1 stop         No info   6218            12   
4         21:35   4h 45m      1 stop         No info  13302             1   

   Journey_month  
0              1  
1              1  
2              1  
3              1  
4              1

In [14]:
Train = Train.dropna() # dropping the NaN value.  we chose to drop it as there is only one NaN value. 

In [15]:
#Train set after transformation
Train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10682 entries, 0 to 10682
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Arrival_Time     10682 non-null  object
 6   Duration         10682 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10682 non-null  object
 9   Price            10682 non-null  int64 
 10  Journey_Date     10682 non-null  int64 
 11  Journey_month    10682 non-null  int64 
dtypes: int64(3), object(9)
memory usage: 1.1+ MB


In [16]:
#Our duration column had time written in this format 2h 50m . 
#To help machine learning algorithm derive useful insights, we will convert this text into numeric.

duration= list(Train["Duration"])

for i in range(len(duration)):
    if len(duration[i].split()) !=2:
        if 'h' in duration[i]:
            duration[i]=duration[i].strip() + ' 0m'
        elif 'm' in duration[i]:
            duration[i]= '0h {}'.format(duration[i].strip())
            
dur_hours=[]
dur_minutes=[]

for i in range(len(duration)):
    dur_hours.append(int(duration[i].split()[0][:-1]))#for examole if duration is 49 mintutes 4 sec then it will reflect like
    dur_minutes.append(int(duration[i].split()[1][:-1]))#0:49:4 and if 2 hours 10 seconds then it will reflect like 2:0:10
    
Train["Duration_Hour"]=dur_hours
Train["Duration_Minutes"]=dur_minutes

Train.drop(labels="Duration", axis=1, inplace=True)  #  dropping the original duration column from training set
           

In [17]:
# Test Set(applyig same code to convert 'Duration' to 'Duration _Hours' and 'Duration_Minutes')

durationT=list(Test["Duration"])

for i in range (len(durationT)):
    if len(durationT[i].split()) !=2:
        if "h" in durationT[i]:
            durationT[i]=durationT[i].strip() + " 0m"
        elif "m" in durationT[i]:
            durationT[i]="0h {}".format(durationT[i].strip())
dur_hours=[]
dur_minutes=[]

for i in range (len(durationT)):
    dur_hours.append(int(durationT[i].split()[0][:-1]))
    dur_minutes.append(int(durationT[i].split()[1][:-1]))
Test["Duration_Hour"]=dur_hours
Test["Duration_Minutes"]=dur_minutes

Test.drop(labels="Duration", axis=1, inplace=True) #  dropping the original duration column from Testing set

In [18]:
Train.info() # checking the data types of all the columns once again. 'Duration_hours' and 'Duration_minutes' are integer type columns

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10682 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Airline           10682 non-null  object
 1   Source            10682 non-null  object
 2   Destination       10682 non-null  object
 3   Route             10682 non-null  object
 4   Dep_Time          10682 non-null  object
 5   Arrival_Time      10682 non-null  object
 6   Total_Stops       10682 non-null  object
 7   Additional_Info   10682 non-null  object
 8   Price             10682 non-null  int64 
 9   Journey_Date      10682 non-null  int64 
 10  Journey_month     10682 non-null  int64 
 11  Duration_Hour     10682 non-null  int64 
 12  Duration_Minutes  10682 non-null  int64 
dtypes: int64(5), object(8)
memory usage: 1.1+ MB


In [19]:
#Converting 'Dep_Time' to 'Depart_Time_hour' and 'Depart_time_Minutes'
#Train Set
Train["Depart_time_hour"]=pd.to_datetime(Train.Dep_Time).dt.hour
Train["Depart_time_minute"]=pd.to_datetime(Train.Dep_Time).dt.minute
Train.drop("Dep_Time",axis=1,inplace=True)
#Test Set
Test["Depart_time_hour"]=pd.to_datetime(Test.Dep_Time).dt.hour
Test["Depart_time_minute"]=pd.to_datetime(Test.Dep_Time).dt.minute
Test.drop("Dep_Time",axis=1,inplace=True)

In [20]:
Train.head() # cheking the training set after transformation

Airline    Source Destination                  Route  Arrival_Time  \
0       IndiGo  Banglore   New Delhi              BLR → DEL  01:10 22 Mar   
1    Air India   Kolkata    Banglore  CCU → IXR → BBI → BLR         13:15   
2  Jet Airways     Delhi      Cochin  DEL → LKO → BOM → COK  04:25 10 Jun   
3       IndiGo   Kolkata    Banglore        CCU → NAG → BLR         23:30   
4       IndiGo  Banglore   New Delhi        BLR → NAG → DEL         21:35   

  Total_Stops Additional_Info  Price  Journey_Date  Journey_month  \
0    non-stop         No info   3897            24              1   
1     2 stops         No info   7662             1              1   
2     2 stops         No info  13882             9              1   
3      1 stop         No info   6218            12              1   
4      1 stop         No info  13302             1              1   

   Duration_Hour  Duration_Minutes  Depart_time_hour  Depart_time_minute  
0              2                50                22                  20  
1              7                25                 5                  50  
2             19                 0                 9                  25  
3              5                25                18                   5  
4              4                45                16                  50

In [21]:
#Converting 'Arr_Time' to 'Arr_Time_hour' and 'Arr_time_Minutes' and dropping the original column
#Train Set
Train["Arrival_time_hour"]=pd.to_datetime(Train.Arrival_Time).dt.hour
Train["Arrival_time_minute"]=pd.to_datetime(Train.Arrival_Time).dt.minute

#Test set
Test["Arrival_time_hour"]=pd.to_datetime(Test.Arrival_Time).dt.hour
Test["Arrival_time_minute"]=pd.to_datetime(Test.Arrival_Time).dt.minute

# dropping the original Arrival_Time column from training and Test Set
Train.drop("Arrival_Time",axis=1,inplace=True)
Test.drop("Arrival_Time",axis=1,inplace=True)

# cheking the test set after transformation
Test.head()

Airline    Source Destination            Route Total_Stops  \
0        Jet Airways     Delhi      Cochin  DEL → BOM → COK      1 stop   
1             IndiGo   Kolkata    Banglore  CCU → MAA → BLR      1 stop   
2        Jet Airways     Delhi      Cochin  DEL → BOM → COK      1 stop   
3  Multiple carriers     Delhi      Cochin  DEL → BOM → COK      1 stop   
4           Air Asia  Banglore       Delhi        BLR → DEL    non-stop   

               Additional_Info  Journey_Date  Journey_month  Duration_Hour  \
0                      No info             6              1             10   
1                      No info            12              1              4   
2  In-flight meal not included            21              1             23   
3                      No info            21              1             13   
4                      No info            24              1              2   

   Duration_Minutes  Depart_time_hour  Depart_time_minute  Arrival_time_hour  \
0                55                17                  30                  4   
1                 0                 6                  20                 10   
2                45                19                  15                 19   
3                 0                 8                   0                 21   
4                50                23                  55                  2   

   Arrival_time_minute  
0                   25  
1                   20  
2                    0  
3                    0  
4                   45

In [22]:
Y_train=Train.iloc[:,6].values # 6 is the index of "Price" in the Training Set , setting it as the label column

# Independent Variables
X_train = Train.iloc[:,Train.columns != 'Price'].values # selects all columns except "Price"

# Independent Variables for Test Set
X_test = Test.iloc[:,:].values

X_train

array([['IndiGo', 'Banglore', 'New Delhi', ..., 20, 1, 10],
       ['Air India', 'Kolkata', 'Banglore', ..., 50, 13, 15],
       ['Jet Airways', 'Delhi', 'Cochin', ..., 25, 4, 25],
       ...,
       ['Jet Airways', 'Banglore', 'Delhi', ..., 20, 11, 20],
       ['Vistara', 'Banglore', 'New Delhi', ..., 30, 14, 10],
       ['Air India', 'Delhi', 'Cochin', ..., 55, 19, 15]], dtype=object)

In [23]:
# From the info above it could be observed that many colmns are of object type. So, converting those categorical columns to numerical columns

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

In [24]:
# Training Set
X_train[:,0] = le.fit_transform(X_train[:,0])
X_train

array([[3, 'Banglore', 'New Delhi', ..., 20, 1, 10],
       [1, 'Kolkata', 'Banglore', ..., 50, 13, 15],
       [4, 'Delhi', 'Cochin', ..., 25, 4, 25],
       ...,
       [4, 'Banglore', 'Delhi', ..., 20, 11, 20],
       [10, 'Banglore', 'New Delhi', ..., 30, 14, 10],
       [1, 'Delhi', 'Cochin', ..., 55, 19, 15]], dtype=object)

In [25]:
X_train[:,1] = le.fit_transform(X_train[:,1])
X_train

array([[3, 0, 'New Delhi', ..., 20, 1, 10],
       [1, 3, 'Banglore', ..., 50, 13, 15],
       [4, 2, 'Cochin', ..., 25, 4, 25],
       ...,
       [4, 0, 'Delhi', ..., 20, 11, 20],
       [10, 0, 'New Delhi', ..., 30, 14, 10],
       [1, 2, 'Cochin', ..., 55, 19, 15]], dtype=object)

In [26]:
X_train[:,2] = le.fit_transform(X_train[:,2])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [27]:
X_train[:,3] = le.fit_transform(X_train[:,3])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [28]:
X_train[:,4] = le.fit_transform(X_train[:,4])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [29]:
X_train[:,5] = le.fit_transform(X_train[:,5])
X_train

array([[3, 0, 5, ..., 20, 1, 10],
       [1, 3, 0, ..., 50, 13, 15],
       [4, 2, 1, ..., 25, 4, 25],
       ...,
       [4, 0, 2, ..., 20, 11, 20],
       [10, 0, 5, ..., 30, 14, 10],
       [1, 2, 1, ..., 55, 19, 15]], dtype=object)

In [30]:
#Applying  similar operations on the Test Set

X_test[:,0] = le.fit_transform(X_test[:,0])

X_test[:,1] = le.fit_transform(X_test[:,1])

X_test[:,2] = le.fit_transform(X_test[:,2])

X_test[:,3] = le.fit_transform(X_test[:,3])

X_test[:,4] = le.fit_transform(X_test[:,4])

X_test[:,5] = le.fit_transform(X_test[:,5])
X_test

array([[4, 2, 1, ..., 30, 4, 25],
       [3, 3, 0, ..., 20, 10, 20],
       [4, 2, 1, ..., 15, 19, 0],
       ...,
       [4, 2, 1, ..., 50, 4, 25],
       [1, 2, 1, ..., 0, 19, 15],
       [6, 2, 1, ..., 55, 19, 15]], dtype=object)

In [31]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [32]:
X_train = sc.fit_transform(X_train)
X_train

array([[-0.41080484, -1.65835945,  2.41653414, ..., -0.2349499 ,
        -1.80043628, -0.8900139 ],
       [-1.26115217,  0.89001433, -0.97381203, ...,  1.36360731,
        -0.05090913, -0.5870944 ],
       [ 0.01436882,  0.04055641, -0.2957428 , ...,  0.0314763 ,
        -1.3630545 ,  0.0187446 ],
       ...,
       [ 0.01436882, -1.65835945,  0.38232644, ..., -0.2349499 ,
        -0.34249699, -0.2841749 ],
       [ 2.56541078, -1.65835945,  2.41653414, ...,  0.2979025 ,
         0.0948848 , -0.8900139 ],
       [-1.26115217,  0.04055641, -0.2957428 , ...,  1.63003351,
         0.82385444, -0.5870944 ]])

In [33]:
X_test = sc.transform(X_test)
X_test

array([[ 0.01436882,  0.04055641, -0.2957428 , ...,  0.2979025 ,
        -1.3630545 ,  0.0187446 ],
       [-0.41080484,  0.89001433, -0.97381203, ..., -0.2349499 ,
        -0.48829092, -0.2841749 ],
       [ 0.01436882,  0.04055641, -0.2957428 , ..., -0.5013761 ,
         0.82385444, -1.4958529 ],
       ...,
       [ 0.01436882,  0.04055641, -0.2957428 , ...,  1.36360731,
        -1.3630545 ,  0.0187446 ],
       [-1.26115217,  0.04055641, -0.2957428 , ..., -1.30065471,
         0.82385444, -0.5870944 ],
       [ 0.86471614,  0.04055641, -0.2957428 , ...,  1.63003351,
         0.82385444, -0.5870944 ]])

In [34]:
# applying similar operation on the Y labels

Y_train=Y_train.reshape(-1, 1)
Y_train = sc.fit_transform(Y_train)
Y_train = Y_train.ravel()
Y_train


array([-1.12553455, -0.30906781,  1.03978296, ..., -0.40296691,
        0.77218138,  0.57809433])

Now our training and test data sets has been seperated which can be used to build a machine learning model now.